vlog -work work E:/Project/Verilog/Computer/simulation/modelsim/sc_computer_test_wave_01.vwf.vt
vsim -novopt -c -t 1ps -L cycloneiv_ver -L altera_ver -L altera_mf_ver -L 220model_ver -L sgate work.sc_computer_vlg_vec_tst
onerror {resume}
add wave {sc_computer_vlg_vec_tst/i1/resetn}
add wave {sc_computer_vlg_vec_tst/i1/clock}
add wave {sc_computer_vlg_vec_tst/i1/pc}
add wave {sc_computer_vlg_vec_tst/i1/pc[31]}
add wave {sc_computer_vlg_vec_tst/i1/pc[30]}
add wave {sc_computer_vlg_vec_tst/i1/pc[29]}
add wave {sc_computer_vlg_vec_tst/i1/pc[28]}
add wave {sc_computer_vlg_vec_tst/i1/pc[27]}
add wave {sc_computer_vlg_vec_tst/i1/pc[26]}
add wave {sc_computer_vlg_vec_tst/i1/pc[25]}
add wave {sc_computer_vlg_vec_tst/i1/pc[24]}
add wave {sc_computer_vlg_vec_tst/i1/pc[23]}
add wave {sc_computer_vlg_vec_tst/i1/pc[22]}
add wave {sc_computer_vlg_vec_tst/i1/pc[21]}
add wave {sc_computer_vlg_vec_tst/i1/pc[20]}
add wave {sc_computer_vlg_vec_tst/i1/pc[19]}
add wave {sc_computer_vlg_vec_tst/i1/pc[18]}
add wave {sc_computer_vlg_vec_tst/i1/pc[17]}
add wave {sc_computer_vlg_vec_tst/i1/pc[16]}
add wave {sc_computer_vlg_vec_tst/i1/pc[15]}
add wave {sc_computer_vlg_vec_tst/i1/pc[14]}
add wave {sc_computer_vlg_vec_tst/i1/pc[13]}
add wave {sc_computer_vlg_vec_tst/i1/pc[12]}
add wave {sc_computer_vlg_vec_tst/i1/pc[11]}
add wave {sc_computer_vlg_vec_tst/i1/pc[10]}
add wave {sc_computer_vlg_vec_tst/i1/pc[9]}
add wave {sc_computer_vlg_vec_tst/i1/pc[8]}
add wave {sc_computer_vlg_vec_tst/i1/pc[7]}
add wave {sc_computer_vlg_vec_tst/i1/pc[6]}
add wave {sc_computer_vlg_vec_tst/i1/pc[5]}
add wave {sc_computer_vlg_vec_tst/i1/pc[4]}
add wave {sc_computer_vlg_vec_tst/i1/pc[3]}
add wave {sc_computer_vlg_vec_tst/i1/pc[2]}
add wave {sc_computer_vlg_vec_tst/i1/pc[1]}
add wave {sc_computer_vlg_vec_tst/i1/pc[0]}
add wave {sc_computer_vlg_vec_tst/i1/inst}
add wave {sc_computer_vlg_vec_tst/i1/inst[31]}
add wave {sc_computer_vlg_vec_tst/i1/inst[30]}
add wave {sc_computer_vlg_vec_tst/i1/inst[29]}
add wave {sc_computer_vlg_vec_tst/i1/inst[28]}
add wave {sc_computer_vlg_vec_tst/i1/inst[27]}
add wave {sc_computer_vlg_vec_tst/i1/inst[26]}
add wave {sc_computer_vlg_vec_tst/i1/inst[25]}
add wave {sc_computer_vlg_vec_tst/i1/inst[24]}
add wave {sc_computer_vlg_vec_tst/i1/inst[23]}
add wave {sc_computer_vlg_vec_tst/i1/inst[22]}
add wave {sc_computer_vlg_vec_tst/i1/inst[21]}
add wave {sc_computer_vlg_vec_tst/i1/inst[20]}
add wave {sc_computer_vlg_vec_tst/i1/inst[19]}
add wave {sc_computer_vlg_vec_tst/i1/inst[18]}
add wave {sc_computer_vlg_vec_tst/i1/inst[17]}
add wave {sc_computer_vlg_vec_tst/i1/inst[16]}
add wave {sc_computer_vlg_vec_tst/i1/inst[15]}
add wave {sc_computer_vlg_vec_tst/i1/inst[14]}
add wave {sc_computer_vlg_vec_tst/i1/inst[13]}
add wave {sc_computer_vlg_vec_tst/i1/inst[12]}
add wave {sc_computer_vlg_vec_tst/i1/inst[11]}
add wave {sc_computer_vlg_vec_tst/i1/inst[10]}
add wave {sc_computer_vlg_vec_tst/i1/inst[9]}
add wave {sc_computer_vlg_vec_tst/i1/inst[8]}
add wave {sc_computer_vlg_vec_tst/i1/inst[7]}
add wave {sc_computer_vlg_vec_tst/i1/inst[6]}
add wave {sc_computer_vlg_vec_tst/i1/inst[5]}
add wave {sc_computer_vlg_vec_tst/i1/inst[4]}
add wave {sc_computer_vlg_vec_tst/i1/inst[3]}
add wave {sc_computer_vlg_vec_tst/i1/inst[2]}
add wave {sc_computer_vlg_vec_tst/i1/inst[1]}
add wave {sc_computer_vlg_vec_tst/i1/inst[0]}
add wave {sc_computer_vlg_vec_tst/i1/aluout}
add wave {sc_computer_vlg_vec_tst/i1/aluout[31]}
add wave {sc_computer_vlg_vec_tst/i1/aluout[30]}
add wave {sc_computer_vlg_vec_tst/i1/aluout[29]}
add wave {sc_computer_vlg_vec_tst/i1/aluout[28]}
add wave {sc_computer_vlg_vec_tst/i1/aluout[27]}
add wave {sc_computer_vlg_vec_tst/i1/aluout[26]}
add wave {sc_computer_vlg_vec_tst/i1/aluout[25]}
add wave {sc_computer_vlg_vec_tst/i1/aluout[24]}
add wave {sc_computer_vlg_vec_tst/i1/aluout[23]}
add wave {sc_computer_vlg_vec_tst/i1/aluout[22]}
add wave {sc_computer_vlg_vec_tst/i1/aluout[21]}
add wave {sc_computer_vlg_vec_tst/i1/aluout[20]}
add wave {sc_computer_vlg_vec_tst/i1/aluout[19]}
add wave {sc_computer_vlg_vec_tst/i1/aluout[18]}
add wave {sc_computer_vlg_vec_tst/i1/aluout[17]}
add wave {sc_computer_vlg_vec_tst/i1/aluout[16]}
add wave {sc_computer_vlg_vec_tst/i1/aluout[15]}
add wave {sc_computer_vlg_vec_tst/i1/aluout[14]}
add wave {sc_computer_vlg_vec_tst/i1/aluout[13]}
add wave {sc_computer_vlg_vec_tst/i1/aluout[12]}
add wave {sc_computer_vlg_vec_tst/i1/aluout[11]}
add wave {sc_computer_vlg_vec_tst/i1/aluout[10]}
add wave {sc_computer_vlg_vec_tst/i1/aluout[9]}
add wave {sc_computer_vlg_vec_tst/i1/aluout[8]}
add wave {sc_computer_vlg_vec_tst/i1/aluout[7]}
add wave {sc_computer_vlg_vec_tst/i1/aluout[6]}
add wave {sc_computer_vlg_vec_tst/i1/aluout[5]}
add wave {sc_computer_vlg_vec_tst/i1/aluout[4]}
add wave {sc_computer_vlg_vec_tst/i1/aluout[3]}
add wave {sc_computer_vlg_vec_tst/i1/aluout[2]}
add wave {sc_computer_vlg_vec_tst/i1/aluout[1]}
add wave {sc_computer_vlg_vec_tst/i1/aluout[0]}
add wave {sc_computer_vlg_vec_tst/i1/memout}
add wave {sc_computer_vlg_vec_tst/i1/memout[31]}
add wave {sc_computer_vlg_vec_tst/i1/memout[30]}
add wave {sc_computer_vlg_vec_tst/i1/memout[29]}
add wave {sc_computer_vlg_vec_tst/i1/memout[28]}
add wave {sc_computer_vlg_vec_tst/i1/memout[27]}
add wave {sc_computer_vlg_vec_tst/i1/memout[26]}
add wave {sc_computer_vlg_vec_tst/i1/memout[25]}
add wave {sc_computer_vlg_vec_tst/i1/memout[24]}
add wave {sc_computer_vlg_vec_tst/i1/memout[23]}
add wave {sc_computer_vlg_vec_tst/i1/memout[22]}
add wave {sc_computer_vlg_vec_tst/i1/memout[21]}
add wave {sc_computer_vlg_vec_tst/i1/memout[20]}
add wave {sc_computer_vlg_vec_tst/i1/memout[19]}
add wave {sc_computer_vlg_vec_tst/i1/memout[18]}
add wave {sc_computer_vlg_vec_tst/i1/memout[17]}
add wave {sc_computer_vlg_vec_tst/i1/memout[16]}
add wave {sc_computer_vlg_vec_tst/i1/memout[15]}
add wave {sc_computer_vlg_vec_tst/i1/memout[14]}
add wave {sc_computer_vlg_vec_tst/i1/memout[13]}
add wave {sc_computer_vlg_vec_tst/i1/memout[12]}
add wave {sc_computer_vlg_vec_tst/i1/memout[11]}
add wave {sc_computer_vlg_vec_tst/i1/memout[10]}
add wave {sc_computer_vlg_vec_tst/i1/memout[9]}
add wave {sc_computer_vlg_vec_tst/i1/memout[8]}
add wave {sc_computer_vlg_vec_tst/i1/memout[7]}
add wave {sc_computer_vlg_vec_tst/i1/memout[6]}
add wave {sc_computer_vlg_vec_tst/i1/memout[5]}
add wave {sc_computer_vlg_vec_tst/i1/memout[4]}
add wave {sc_computer_vlg_vec_tst/i1/memout[3]}
add wave {sc_computer_vlg_vec_tst/i1/memout[2]}
add wave {sc_computer_vlg_vec_tst/i1/memout[1]}
add wave {sc_computer_vlg_vec_tst/i1/memout[0]}
add wave {sc_computer_vlg_vec_tst/i1/mem_clk}
add wave {sc_computer_vlg_vec_tst/i1/imem_clk}
add wave {sc_computer_vlg_vec_tst/i1/dmem_clk}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[6]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[6][31]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[6][30]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[6][29]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[6][28]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[6][27]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[6][26]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[6][25]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[6][24]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[6][23]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[6][22]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[6][21]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[6][20]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[6][19]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[6][18]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[6][17]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[6][16]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[6][15]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[6][14]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[6][13]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[6][12]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[6][11]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[6][10]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[6][9]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[6][8]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[6][7]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[6][6]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[6][5]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[6][4]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[6][3]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[6][2]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[6][1]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[6][0]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[5]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[5][31]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[5][30]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[5][29]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[5][28]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[5][27]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[5][26]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[5][25]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[5][24]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[5][23]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[5][22]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[5][21]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[5][20]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[5][19]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[5][18]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[5][17]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[5][16]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[5][15]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[5][14]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[5][13]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[5][12]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[5][11]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[5][10]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[5][9]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[5][8]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[5][7]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[5][6]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[5][5]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[5][4]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[5][3]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[5][2]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[5][1]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[5][0]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[4]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[4][31]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[4][30]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[4][29]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[4][28]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[4][27]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[4][26]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[4][25]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[4][24]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[4][23]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[4][22]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[4][21]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[4][20]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[4][19]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[4][18]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[4][17]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[4][16]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[4][15]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[4][14]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[4][13]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[4][12]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[4][11]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[4][10]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[4][9]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[4][8]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[4][7]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[4][6]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[4][5]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[4][4]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[4][3]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[4][2]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[4][1]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[4][0]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[3]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[3][31]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[3][30]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[3][29]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[3][28]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[3][27]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[3][26]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[3][25]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[3][24]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[3][23]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[3][22]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[3][21]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[3][20]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[3][19]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[3][18]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[3][17]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[3][16]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[3][15]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[3][14]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[3][13]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[3][12]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[3][11]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[3][10]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[3][9]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[3][8]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[3][7]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[3][6]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[3][5]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[3][4]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[3][3]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[3][2]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[3][1]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[3][0]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[2]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[2][31]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[2][30]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[2][29]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[2][28]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[2][27]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[2][26]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[2][25]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[2][24]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[2][23]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[2][22]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[2][21]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[2][20]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[2][19]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[2][18]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[2][17]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[2][16]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[2][15]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[2][14]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[2][13]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[2][12]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[2][11]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[2][10]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[2][9]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[2][8]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[2][7]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[2][6]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[2][5]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[2][4]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[2][3]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[2][2]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[2][1]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[2][0]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[1]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[1][31]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[1][30]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[1][29]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[1][28]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[1][27]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[1][26]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[1][25]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[1][24]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[1][23]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[1][22]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[1][21]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[1][20]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[1][19]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[1][18]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[1][17]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[1][16]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[1][15]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[1][14]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[1][13]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[1][12]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[1][11]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[1][10]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[1][9]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[1][8]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[1][7]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[1][6]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[1][5]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[1][4]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[1][3]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[1][2]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[1][1]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[1][0]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[7]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[7][31]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[7][30]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[7][29]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[7][28]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[7][27]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[7][26]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[7][25]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[7][24]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[7][23]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[7][22]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[7][21]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[7][20]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[7][19]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[7][18]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[7][17]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[7][16]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[7][15]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[7][14]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[7][13]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[7][12]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[7][11]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[7][10]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[7][9]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[7][8]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[7][7]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[7][6]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[7][5]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[7][4]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[7][3]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[7][2]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[7][1]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[7][0]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[8]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[8][31]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[8][30]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[8][29]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[8][28]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[8][27]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[8][26]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[8][25]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[8][24]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[8][23]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[8][22]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[8][21]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[8][20]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[8][19]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[8][18]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[8][17]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[8][16]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[8][15]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[8][14]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[8][13]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[8][12]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[8][11]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[8][10]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[8][9]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[8][8]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[8][7]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[8][6]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[8][5]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[8][4]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[8][3]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[8][2]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[8][1]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[8][0]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[9]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[9][31]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[9][30]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[9][29]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[9][28]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[9][27]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[9][26]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[9][25]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[9][24]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[9][23]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[9][22]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[9][21]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[9][20]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[9][19]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[9][18]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[9][17]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[9][16]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[9][15]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[9][14]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[9][13]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[9][12]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[9][11]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[9][10]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[9][9]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[9][8]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[9][7]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[9][6]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[9][5]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[9][4]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[9][3]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[9][2]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[9][1]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[9][0]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[10]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[10][31]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[10][30]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[10][29]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[10][28]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[10][27]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[10][26]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[10][25]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[10][24]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[10][23]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[10][22]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[10][21]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[10][20]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[10][19]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[10][18]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[10][17]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[10][16]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[10][15]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[10][14]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[10][13]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[10][12]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[10][11]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[10][10]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[10][9]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[10][8]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[10][7]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[10][6]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[10][5]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[10][4]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[10][3]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[10][2]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[10][1]}
add wave {sc_computer_vlg_vec_tst/i1/cpu/rf/register[10][0]}
run -all
